config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'source#index'
  get 'source/about'
  get 'source/index'
  get 'source/saved'
  post 'source/download' => 'source#download'
  post 'source/download_all' => 'source#download_all'
  post 'source/saved'
  delete "source/delete", to: "source#delete", as: "delete"

  post "source/:saved", to: "source#saved", as: "save"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reference.rb
class Reference < ActiveRecord::Base
    validates_presence_of :url

   self.abstract_class = true

    def self.scrape_references (wiki_link)
      raise "Nil URL" if wiki_link.nil?
      file = URI.open(wiki_link)
      page_data = Nokogiri::HTML5(file)
      page_data.css('style').remove # Removes a style glitch inside reference classes on some wiki pages by mediawiki api
      page_data.css('.reflist-lower-alpha').remove # Remove cite notes
      reflist = page_data.css('.reference-text') # Only grabs data from class 'reference-text'
      
      content_array = [] # holds reference info
      url_array = [] # holds reference link
      source_hash = [] # info is key, link is data
      i = 0

      reflist.each do |reference| 
          content = reference.text
          if (reference.css('a').attribute('href') != nil)
	          url = reference.css('a').attribute('href').value
	          content.tr!('"', '') # remove backslashes
	          url.tr!('"', '') # remove backslashes
					else
						url = reference.css('a').attribute('href')
						content.tr!('"', '') # remove backslashes
					end

          content_array[i] = content.strip
          url_array[i] = url  
          i += 1

          # I tried below but it only works for some pages, breaks others
          #if (url.include? '/wiki/ISBN') etc
          #elseif (url.include? '#CITEREF') etc
          # link these citerefs to their links in the reflist that follows
      end
      source_hash = Hash[content_array.zip(url_array)]
      # return source_hash
  end 
end
  

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    attr_accessor :sourcelist
    # validates_presence_of :sourcelist, presence: true
       
    def self.save_a_source(new_source,sourcelist)
      sourcelist=sourcelist.append(new_source)
      
      

      

      
        return(sourcelist)
        
      end
       
    def self.show_sources(saved_sourcelist)
        return saved_sourcelist 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/source_controller.rb
class SourceController < ApplicationController
  def index
    if(params["search"] == nil)
      params["search"] = ""
    end
    #the views would work best if this sources instance variable was a hash
    @link = params["search"]
    if valid_url?(@link) == true
      @sources = Reference.scrape_references(params["search"])
      @page = Wikipedia.find(params["search"])
    else
      @page = Wikipedia.find(params["search"])
      @link = @page.fullurl
      @sources = Reference.scrape_references(@link)
        if @sources == nil
          # Handle dismbiguation in future
        end
    end
    if @sources[:status] == :completed && @sources[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:notice] = "Unable to find references from given URL"
    end
    rescue StandardError => e
      flash.now[:alert] = "Error: #{e}" 
  end

  def valid_url?(url)
    return false if url.include?("<script")
    url_regexp = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
    url =~ url_regexp ? true : false
  end

  def about
  end 
#
  # still must save in model
  def saved
    @sourcelist = ["https://sourcely-group4.herokuapp.com/"]
    if params[:saveditem]
  
      @saved_sources = User.save_a_source(params[:saveditem], @sourcelist)
      @saved_sources=User.save_a_source(params[:saveditem],[:saveditem])
      end
    @saved_sources = User.show_sources(@sourcelist)
  end

  def download
    if params[:output]
      File.open("sourcely.txt", 'w') do |f|
        f.puts(params[:output])
        send_file(f)
      end
    end
  rescue Errno::ENOENT
  end

  # uccs wikipedia page is an example of a page that
  # the download all formatting doesn't work on
  # Works for most, there's a problem w/specific source lists
  def download_all
    if params[:output]
      File.open("sourcely.txt", 'w') do |f|
        f.puts(params[:output])
          temp = File.read(f)
          # The last part of the below expression deletes all commas
          # Ideally, we want to remove commas follwed by a newline or spaces
          # That way we could preserve description commas
          replace = temp.to_s.gsub!(/\"/,"\n")
          replace = replace.to_s.tr('{}', '')
          replace = replace.to_s.gsub!(/\,/,"")
          File.open("sourcely.txt", "w") {|f| f.puts replace }
        send_file(f)
      end
    end
  rescue Errno::ENOENT
  end

 

  # Downloading works now but the file isn't being deleted
  # Ruby returns the delete if it's left after send_file 
  # so it was returning the deleted file
  # Will need to delete seperately or send_file from a different function
  # If the name of the file is made dynmaic the file must be deleted.
  # This is how file deletion would work if time permitted adding it:
  # https://stackoverflow.com/questions/8530379/delete-the-file-from-the-server-after-the-download-is-completed

  def delete
    if params[:output]
      #arrays can just do .delete(args) and it will remove that value
      #when the model for the user is set up use the array of saved sources and use:
      #@saved_sources.delete(params[:output])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/source_helper.rb
module SourceHelper
end

app/views/layouts/_error_page.html.erb
<body>
    <div class="container-fluid">
        <div class="container">
            <h1>Error</h1>
        </div>
        <div class="container">
            <p>
                Looks like this isn't a wikipedia article, or there's an error.
            </p>
        </div>
</body>

app/views/layouts/_faq.html.erb
<body>
    <div class="container-fluid">
        <div class="container">
            <h1>Error</h1>
        </div>
        <div class="container">
            <p>
                Looks like this isn't a wikipedia article, or there's an error.
            </p>
        </div>
</body>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-lg navbar-light">

  <a class="navbar-brand" href="../">Sourcely</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <%= link_to 'About' , source_about_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to 'Saved' , source_saved_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign out' , destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Register' , new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign in' , new_user_session_path, class: 'nav-link' %>
      </li>
      <% end %>

    </ul>
  </div>
</nav>
</header>
<title>Sourcely</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <br> <br> 
  <nav class="navbar navbar-light">
  <a class="navbar-brand"></a>
  <form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Wikipedia URL" aria-label="Search" id="search" name="search">
      <button type="submit" class="btn btn-outline-secondary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
        </svg>
      </button>
  </form>
  <form class="form-inline">
    <a class="navbar-brand mr-auto" href="#">
    </a>
  </form>
</nav>
<center>
<a href="https://en.wikipedia.org/wiki/Main_Page" target="_blank">Wikipedia</a> | <a href="https://en.wikipedia.org/wiki/Special:Random" target="_blank">Random</a>
</center>

app/views/layouts/_navbar_not_index.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-lg navbar-light">

  <a class="navbar-brand" href="../">Sourcely</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <%= link_to 'About' , source_about_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to 'Saved' , source_saved_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign out' , destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Register' , new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign in' , new_user_session_path, class: 'nav-link' %>
      </li>
      <% end %>


      
      

    </ul>
  </div>
</nav>
</header>
<title>Sourcely</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  <nav class="navbar navbar-light">
  <a class="navbar-brand"></a>

  
  <form class="form-inline">
    <a class="navbar-brand mr-auto" href="#">

    </a>
  </form>
</nav>

app/views/layouts/_saved.html.erb
<% if user_signed_in? %>

<body class = "section">
    <div class="container-fluid col-md-10" style="background-color:#f5fffa">
        <br>
        <h2 style="margin-left: 2px;">Saved</h2><hr>
        <div class="col-lg-16"style="margin: 1px 1px 5px 5px">
            <span><a href="#"><u>Source</u></a></span>    
            <button type="button" class="btn ml-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#14866d" class="bi bi-collection-fill" viewBox="0 0 16 16">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#14866d" class="bi bi-save-fill" viewBox="0 0 16 16">
                    <path d="M8.5 1.5A1.5 1.5 0 0 1 10 0h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h6c-.314.418-.5.937-.5 1.5v7.793L4.854 6.646a.5.5 0 1 0-.708.708l3.5 3.5a.5.5 0 0 0 .708 0l3.5-3.5a.5.5 0 0 0-.708-.708L8.5 9.293V1.5z"/>
                </svg>
            </button>
            <button type="button" class="btn ml-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#b32425" class="bi bi-collection-fill" viewBox="0 0 16 16">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#b32425" class="bi bi-trash-fill" viewBox="0 0 16 16">
                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                </svg>
            </button>
        </div>
        <div class="col-md-12 text-center mb-1">

        </div>
        <br>
    </div>
<body>
<br>
<%else%>

<%end%>

app/views/layouts/_sources-container.html.erb
<!DOCTYPE html>
<html lang="en">
    <br>
    <body>
        <div class="container-fluid col-md-10" style="background-color:#eaf3ff"> 
        <div style="padding: 0px">
            <br><h2><strong><%= @page.title %></strong></h2>
        </div>
            <hr>
        <div style="padding: 0px">
            <h5> Summary </h5>
            <p> <%= @page.summary %> </p>
        </div> 
        <hr> 
            <div style="padding: 0px">
            <%= button_to "Download All", {:controller => :source, :action => :download_all}, params:{output: @sources}, class: 'btn btn-success' %>
            </div>
            <hr>
            <div id="linkcolor">
	            <% @sources.each do |description,link,saved| %>
                    <div class="flex-container">
                        <div class="col"  style="padding: 0px">
                            <%= link_to description, link, target: :_blank %> 
                        </div>
                        <% if user_signed_in? %>
                        <div class="move-down">
                        <div class='btn-group form-btn-group'>
                                <div class="float-right" >	
                                    <%= button_to "Download", {:controller => :source, :action => :download}, params:{output: link}, class: 'btn btn-outline-primary btn-sm' %>	
                                </div>
                                <div class="float-right" >				
                                    <%= button_to "Save", {:controller => :source, :action => :saved}, params:{saveditem: link}, class: 'btn btn-outline-primary btn-sm' %>	
                                </div>			
                        </div>
                        </div>
                        <% end %>
                    </div>
                    <hr>
                <% end %>
            </div>
            <%= button_to "Download All", {:controller => :source, :action => :download_all}, params:{output: @sources}, class: 'btn btn-success' %>
            <hr>
            <div id="bottom">
            </div>
            
        </div>
    </body>
	<center>
	    <br>
	    <a href="#top">Scroll Up</a>
	</center>
</html> 

app/views/layouts/saved.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "application" %>
<html lang="en">

<head>
<meta charset="UTF-8" />
<meta name="viewport"
      content="width=device-width, 
               initial-scale=1.0" />
<title>Sourcely - Saved</title>
</head>

<body class = "section">
<div class = "container-fluid">
<%= render 'layouts/navbar_not_index' %>
<center>
      <div class = "container-fluid">
      <h2>My Saved Sources</h2>
      </div>
      <i class="bi bi-download"></i>
</center>
<div class="container-fluid col-md-10" style="background-color:#eaf3ff"> 
<br>
<div class="col-md-12 text-center mb-1">
<%= button_to "Download All", {:controller => :source, :action => :download}, params:{output: @sourcelist}, class: 'btn btn-success' %>
<br>

</div>
<br>
<% @sourcelist.each do |Saved| %>
      <span>                  
      <div id="linkcolor">
            <div class="row">
            <div class="col-9">
            <%= link_to saved, saved, target: :_blank %>   
            </div>
            <div class="col">
            <%= button_to "Download", {:controller => :source, :action => :download}, params:{output: saved}, class: 'btn btn-outline-success btn-sm' %> 
            </div>
            <div class="col">
            <%= button_to "Delete", {:controller => :source, :action => delete}, params:{output: saved}, class: 'btn btn-outline-danger btn-sm' %>
            </div>
            </div>
      </span>
      <br>
      <br>
<% end %>
<br>
</div>
</div>
<br>
</html>

app/views/source/about.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "application" %>
<html lang="en">

<head>
<meta charset="UTF-8" />
<meta name="viewport"
      content="width=device-width, 
               initial-scale=1.0" />
<title>About Sourcely</title>
</head>

<body class = "section">
<div class = "container-fluid">
<%= render 'layouts/navbar_not_index' %>
<div class="container-fluid col-md-10" style="background-color:#eaf3ff">
    <div class="col-lg-20">
    <br>
        <h1>About Sourcely</h1>
    </div>
    <div class="col-lg-16">
        <p>
            Sourcely is a tool that allows anyone to acquire a list of references from any Wikipedia page!</p>
        <p>
            Our goal is to create a minimalist tool that's easy to use. The purpose of Sourcely is to help people research topics, using Wikipedia as their starting point. </p>
    </div>


    <footer class="container">
    <div class="d-flex justify-content-center"><%= link_to "Start Searching!", source_index_path %></div>
    <br>
    </footer>
    </div>
    </div>
    </div>
</html>

app/views/source/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Sourcely</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "source/home" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  
  </body>
</html>

app/views/source/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport"
          content="width=device-width, 
                   initial-scale=1.0" />

    <% if @sources %>
    <title><%= @page.title %> Sources </title>
    <% end %>
  </head>

  <body class = "section">
  <div id="top">
  </div>
    <div class = "container-fluid">
      <%= render 'layouts/navbar' %>
      <% if @sources %>
          <center>
          <a href="#bottom">Scroll Down</a>
          </center>
          <%= render 'layouts/sources-container' %>

      <% end %>
    </div>

    <div id="bottom">
    <br>
</html>